### ISSUE TITLE
[Bug]: Banner text displayed incompletely on my phone

### ISSUE THREAD

**Issue by GGabirel** [WangJie0822/Cashbook#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

For starters, thanks for your dedication. Good job!
But the banner text seems weird on my phone (Huawei P40 with HarmonyOS 4.0).
It displayed incompletely, which is sort of a nuisance. I have tried to pull down, but no luck. The text is still incomplete.
If you are willing to troubleshoot, I would be more than grateful!
![5a016a50d7427acee9c0d375a79c531](https://github.com/WangJie0822/Cashbook/assets/118699236/3c419645-b292-4864-8e1b-70a16c6e6d9e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WangJie0822** [comment]
This bug is fixed in [Release v1.0.6](https://github.com/WangJie0822/Cashbook/releases/tag/v1.0.6_24082118)
