### ISSUE TITLE
我的资产中充值账户复选框功能

### ISSUE THREAD

**Issue by ZERO624** [WangJie0822/Cashbook#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

升级新版本后，充值账户是否计入总资产复选框功能没有了

### Describe the solution

新版本是否能恢复该功能

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WangJie0822** [comment]
最新预览版本已经添加此功能
