### ISSUE TITLE
[FR]: 能否增加账单图片功能，从本地调用图片，加上这个基本就完美了

### ISSUE THREAD

**Issue by Qifei88623** [WangJie0822/Cashbook#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

能否增加账单图片功能，从本地调用图片，加上这个基本就完美了

### Describe the solution

能否增加账单图片功能，从本地调用图片，加上这个基本就完美了

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by WangJie0822** [comment]
[v1.0.7_24090919_pre](https://github.com/WangJie0822/Cashbook/releases/tag/v1.0.7_24090919_pre) 版本已实现

**Comment by mikuyourworld** [comment]
我感觉他说的不是软件的背景图，而是某一次记录可以添加一个或多个图片，比如买菜的小票，就不用挨个记录，拍照记录个总金额就行。
