### ISSUE TITLE
十分感谢开源

### ISSUE THREAD

**Issue by est7** [WangJie0822/Cashbook#2]
平时项目基本不碰sql,看这个项目代码让我受益良多,比那些各种demo sample水平不知道高多了,就是选koin,coil没选hilt和glide是因为项目练手试试吗?那咋不试试Ktor就全了hh

**Comment by WangJie0822** [comment]
因为用的是kotlin，所以比较偏向使用了kotlin特性的库，Ktor之前没用过，后面我了解一下

**Comment by WangJie0822** [comment]
最新的compose分支使用了hilt

**Comment by est7** [comment]
@WangJie0822 awesome ,我会拉下来继续学习的!
