### ISSUE TITLE
[Bug]: 勾选仅保留最新备份后,备份会删除备份目录下的所有文件/文件夹

### ISSUE THREAD

**Issue by bambooGHT** [WangJie0822/Cashbook#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!如题,非常恐怖

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WangJie0822** [comment]
这个目前设计就是这样的，目前的备份恢复本职上是从备份的数据库文件中查询所有数据，更新到手机数据库里面，旧的备份文件是没有意义的，我之前发现本地备份文件太多了，所以加了这个功能，本地备份只保留最后一个

**Comment by bambooGHT** [comment]
我的意思是会删除备份目录下的所有文件,不仅仅是备份的文件,如果用户选了一个有其他重要的文件的目录,这个是恐怖的

**Comment by WangJie0822** [comment]
我明白你的意思了，这个之前确实没有考虑到，后续版本会修复此问题

**Comment by WangJie0822** [comment]
已在 [v1.0.7_24123115_pre](https://github.com/WangJie0822/Cashbook/releases/tag/v1.0.7_24123115_pre) 版本修复此问题
