### ISSUE TITLE
[FR]: 增加快速记账入口

### ISSUE THREAD

**Issue by TmcWen** [WangJie0822/Cashbook#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

总感觉单独打开app很麻烦，总有会忘记的时候。能否加入一个快速打开记账的入口？

### Describe the solution

比如通知栏常驻，点击即可弹出记账弹窗。或者又是物理快捷键，比如双击电源键弹出记账弹窗？ 最好的话这个弹出的还是个小弹窗，而不是跳转到activit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WangJie0822** [comment]
已在 [v1.0.7_24123115_pre](https://github.com/WangJie0822/Cashbook/releases/tag/v1.0.7_24123115_pre) 添加应用图标快捷方式，通知栏常驻需要应用后台常驻，暂不计划添加
