### ISSUE TITLE
发现了几个问题

### ISSUE THREAD

**Issue by kleaves** [WangJie0822/Cashbook#5]
您好，在使用过程中发现了几个问题，希望您能够处理一下

- 不支持自建webdav
  - Android P 开始是默认禁止访问http的API
  - 不支持非正规CA证书
- 新版备份
  - 当备份路径（如Downloads）设置和**BACKUP_DIR_NAME**不同时，会在Downloads目录生成多余的备份文件
- webdav备份失败仍提示成功

**Comment by WangJie0822** [comment]
感谢反馈！
- 不支持自建webdav：因为之前一直用的坚果云，没有尝试过自建webdav，所以没有考虑到这个问题，后续我会自建尝试一下进行修复；
- 新版备份：这个功能加上是因为最近一直在 develop-compose 分支尝试使用compose重构，为了方便可以直接从正式版本读取数据用于测试的，所以不建议使用，对应的恢复功能仅在compose版本上线；
- webdav备份失败仍提示成功：备份功能是本地+云端两个逻辑先后执行的，只要本地成功了就会提示成功，因为不确定你遇到的是什么场景，所以没有更多建议，如果还有疑问还请提供更多信息；
> 因为工作原因以及最近可能更多尽力花在了compose版本上，所以这个应用之前规划的功能还未能完成，备份数据是通用的，没有限制签名，可以尝试自己完善，还是感谢您的反馈，很惊喜除了我自己还有人在用这个不完善的工具，谢谢

**Comment by WangJie0822** [comment]
webdav http协议闪退的问题修复了
