### ISSUE TITLE
关于导出导入功能

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [WangJie0822/Cashbook#6]
### 导入
比如可否支持从微信导出的csv导入到大佬的软件里
### 导出
可否支持导出已存在的账本格式为csv或excel啥的都可以

还有一些别的小想法，比如`编辑账本`-`顶部图片背景`可否调用系统文件选择器，以选择本地图片
而且releases里能否同时提供纯本地版本，虽然开源的代码很放心，但有的人因为单纯的心理作用并不希望这类软件联网(比如我...虽然可以在系统里禁掉联网)
p.s.大佬可以嫖GitHubAction编译的，花几分钟写个workflow就好，你的每次commit都可以自动编译上传，这样别人就能直接玩到你的测试版本了~

**Comment by WangJie0822** [comment]
好的，感谢你的意见，我会加个代办项，后续会陆续加上的

**Comment by WangJie0822** [comment]
纯本地版本已上线，workflow也已经加上了
