### ISSUE TITLE
[Bug]: 导入旧版备份，我的资产页面的资产全部为0

### ISSUE THREAD

**Issue by kleaves** [WangJie0822/Cashbook#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

如题

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WangJie0822** [comment]
麻烦提供一下旧版备份的版本，以及导入备份新版本的版本

**Comment by kleaves** [comment]
旧版本为v0.6.2_23090515，新版本为11月14号代码自编译

**Comment by WangJie0822** [comment]
0.6.2 版本的备份数据和 1.0.0 之后的compose 版本备份数据是不兼容的，需要在0.6.2版本导出为新版本备份才能在compose版本用于恢复
